[package]
name = "libclipboard"
version = "0.2.0"
authors = ["feenk gmbh <contact@feenk.com>"]
edition = "2021"

[dependencies]
copypasta = "0.8.1"
value-box = "1.1"
string-box = "1.1"

[lib]
name = "Clipboard"
crate-type = ["cdylib"]