[package]
name = "libclipboard"
version = "1.0.0"
authors = ["feenk gmbh <contact@feenk.com>"]
edition = "2021"

[dependencies]
copypasta = "0.8.1"
value-box = { version = "2.2", features = [ "phlow" ] }
string-box = "1.1"
value-box-ffi = { version = "1.0", features = [ "string-box", "phlow" ] }
phlow = "1.3"
phlow-extensions = "1.3"
phlow-ffi = { version = "1.0" }

[lib]
name = "Clipboard"
crate-type = ["cdylib"]
